name: final-project-build
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
      build:
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v4
            with:
              clean: false
              submodules: 'recursive'
          - name: Run build
            timeout-minutes: 600
            run: ./build.sh
